const deck = [
  {
    cardIndex: '',
    cardName: 'Name Template 01',
    cardDescription: '',
    cardAttr1: '10',
    cardAttr2: '20',
    cardAttr3: '30',
    cardImage: '',
    cardRare: 'normal',
    cardTrunfo: false,
    isPreview: false,
  },
  {
    cardIndex: '',
    cardName: 'Name Template 02',
    cardDescription: '',
    cardAttr1: '15',
    cardAttr2: '25',
    cardAttr3: '35',
    cardImage: 'https://xurras.co/_library/images/default-avatar.jpg',
    cardRare: 'raro',
    cardTrunfo: false,
    isPreview: false,
  },
  {
    cardIndex: '',
    cardName: 'Name Template 03',
    cardDescription: '',
    cardAttr1: '20',
    cardAttr2: '30',
    cardAttr3: '40',
    cardImage: 'https://xurras.co/_library/images/default-avatar.jpg',
    cardRare: 'muito raro',
    cardTrunfo: false,
    isPreview: false,
  },
  {
    cardIndex: '',
    cardName: 'Name Template 04',
    cardDescription: '',
    cardAttr1: '30',
    cardAttr2: '20',
    cardAttr3: '10',
    cardImage: 'https://xurras.co/_library/images/default-avatar.jpg',
    cardRare: 'normal',
    cardTrunfo: false,
    isPreview: false,
  },
];

export default deck;
