const Data = [
  {
    name: 'Braquiossauro',
    description: 'Herbívoro',
    attr: {
      attr1: 12,
      attr2: 26,
      attr3: 50,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/2/5/6/1_brachiosaurus_braquiossauro_22652_2_600.webp',
    rare: 'raro',
    isTrunfo: false,
  },
  {
    name: 'Diplodoco',
    description: 'Herbívoro',
    attr: {
      attr1: 9,
      attr2: 35,
      attr3: 50,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/2/5/6/2_diplodocus_diplodoco_22652_3_600.webp',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Estegossauro',
    description: 'Herbívoro',
    attr: {
      attr1: 4,
      attr2: 9,
      attr3: 6,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/2/5/6/3_stegosaurus_estegossauro_22652_4_600.webp',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Tricerátopo',
    description: 'Herbívoro',
    attr: {
      attr1: 4,
      attr2: 10,
      attr3: 10,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/2/5/6/4_triceratops_triceratopo_22652_5_600.webp',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Protoceratops',
    description: 'Herbívoro',
    attr: {
      attr1: 0.6,
      attr2: 1,
      attr3: 0.01,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/2/5/6/5_protoceratops_22652_6_600.webp',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Patagotitan Mayorum',
    description: 'Herbívoro',
    attr: {
      attr1: 20,
      attr2: 37,
      attr3: 69,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/2/5/6/6_patagotitan_mayorum_22652_7_600.webp',
    rare: 'raro',
    isTrunfo: false,
  },
  {
    name: 'Titanoboa',
    description: 'Carnivoro',
    attr: {
      attr1: 1.1,
      attr2: 13,
      attr3: 1.1,
    },
    image: 'http://chc.org.br/wp-content/uploads/2020/12/bicho_1.jpg',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Crocodilo imperador',
    description: 'Carnivoro',
    attr: {
      attr1: 1.8,
      attr2: 12,
      attr3: 8,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/4/2/2/_23224_1_600.webp',
    rare: 'raro',
    isTrunfo: false,
  },
  {
    name: 'Megalodonte',
    description: 'Carnivoro',
    attr: {
      attr1: 4,
      attr2: 18,
      attr3: 50,
    },
    image: 'https://img.olhardigital.com.br/wp-content/uploads/2022/03/megalodonte-aguas-frias-capa.jpg',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Ave do terror',
    description: 'Carnivoro',
    attr: {
      attr1: 2.5,
      attr2: 18,
      attr3: 0.35,
    },
    image: 'https://t1.ea.ltmcdn.com/pt/posts/4/2/2/_23224_3_600.webp',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Arthropleura',
    description: 'Carnivoro',
    attr: {
      attr1: 0.8,
      attr2: 2.6,
      attr3: 0.15,
    },
    image: 'https://t2.ea.ltmcdn.com/pt/posts/4/2/2/_23224_4_600.webp',
    rare: 'raro',
    isTrunfo: false,
  },
  {
    name: 'Tigre Dentes de Sabre Sul Americano',
    description: 'Carnivoro',
    attr: {
      attr1: 1.2,
      attr2: 2.1,
      attr3: 0.4,
    },
    image: 'https://t1.ea.ltmcdn.com/pt/posts/4/2/2/animais_pre_historicos_brasileiros_23224_5_600.webp',
    rare: 'muito raro',
    isTrunfo: false,
  },
  {
    name: 'Prionossuco',
    description: 'Carnivoro',
    attr: {
      attr1: 1,
      attr2: 9,
      attr3: 2.7,
    },
    image: 'https://t1.ea.ltmcdn.com/pt/posts/4/2/2/_23224_6_600.webp',
    rare: 'raro',
    isTrunfo: false,
  },
  {
    name: 'Chiniquodon',
    description: 'Ornivoro',
    attr: {
      attr1: 0.3,
      attr2: 0.4,
      attr3: 0.01,
    },
    image: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8e0657fd-321b-49fe-941e-c71ef10a532b/ddyryvh-5b7d395e-ce37-432c-a6e0-1061b6fbfe1e.png/v1/fill/w_1600,h_1200,strp/chiniquodon_by_cisiopurple_ddyryvh-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzhlMDY1N2ZkLTMyMWItNDlmZS05NDFlLWM3MWVmMTBhNTMyYlwvZGR5cnl2aC01YjdkMzk1ZS1jZTM3LTQzMmMtYTZlMC0xMDYxYjZmYmZlMWUucG5nIiwiaGVpZ2h0IjoiPD0xMjAwIiwid2lkdGgiOiI8PTE2MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uud2F0ZXJtYXJrIl0sIndtayI6eyJwYXRoIjoiXC93bVwvOGUwNjU3ZmQtMzIxYi00OWZlLTk0MWUtYzcxZWYxMGE1MzJiXC9jaXNpb3B1cnBsZS00LnBuZyIsIm9wYWNpdHkiOjk1LCJwcm9wb3J0aW9ucyI6MC40NSwiZ3Jhdml0eSI6ImNlbnRlciJ9fQ.26aoAseYh38RpVJ7EVeq8bc02jNV5CNczj_LNhMzEfI',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Caiuajara',
    description: 'Carnivoro',
    attr: {
      attr1: 1.3,
      attr2: 2.35,
      attr3: 0.08,
    },
    image: 'https://t1.ea.ltmcdn.com/pt/posts/4/2/2/_23224_10_600.webp',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Preguiça-gigante brasileira',
    description: 'Ornivoro',
    attr: {
      attr1: 6,
      attr2: 6,
      attr3: 4,
    },
    image: 'https://t1.ea.ltmcdn.com/pt/posts/4/2/2/_23224_11_600.webp',
    rare: 'raro',
    isTrunfo: false,
  },
  {
    name: 'Mamute',
    description: 'Herbivoro',
    attr: {
      attr1: 5.3,
      attr2: 7,
      attr3: 17,
    },
    image: 'https://s2.glbimg.com/TEfqi1-40IvUO40mHnvblk3XHYQ=/e.glbimg.com/og/ed/f/original/2021/08/13/mammoth_painting_havens-768x649.jpg',
    rare: 'muito raro',
    isTrunfo: false,
  },
  {
    name: 'Doedicurus',
    description: 'Herbivoro',
    attr: {
      attr1: 1.65,
      attr2: 4,
      attr3: 2,
    },
    image: 'http://pm1.narvii.com/6425/bf24461fd3e32db470b07c633f5e1b86a9fd9630_00.jpg',
    rare: 'normal',
    isTrunfo: false,
  },
  {
    name: 'Anquilossauro',
    description: 'Herbivoro',
    attr: {
      attr1: 1.7,
      attr2: 8,
      attr3: 8,
    },
    image: 'https://i.pinimg.com/736x/1c/f8/b8/1cf8b80fabaabe4b29c1f46c10e16805.jpg',
    rare: 'raro',
    isTrunfo: false,
  },
  {
    name: 'Basilossauro',
    description: 'Carnivoro',
    attr: {
      attr1: 3,
      attr2: 18,
      attr3: 40,
    },
    image: 'http://4.bp.blogspot.com/_DAAcHJHDRPU/Sq0QBb0z4UI/AAAAAAAAFv0/JtTYfEZT3TY/w1200-h630-p-k-no-nu/Basilosaurus+%284%29.jpg',
    rare: 'normal',
    isTrunfo: false,
  },
];

export default Data;
