const array = [
  {
    cardName: 'Homem Aranha',
    cardImage: 'https://s.aficionados.com.br/imagens/poderes-1-0.jpg',
    cardDescription: 'É o amigo da  vizinhança. É o homem aranha!',
    cardAttr1: '70',
    cardAttr2: '50',
    cardAttr3: '79',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Hulk',
    cardImage: 'https://s.aficionados.com.br/imagens/verde-de-raiva-0.jpg',
    cardDescription: 'O incrível Hulk! Não o deixe nervoso!',
    cardAttr1: '88',
    cardAttr2: '60',
    cardAttr3: '10',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Homem de Ferro',
    cardImage: 'https://s.aficionados.com.br/imagens/homem-de-ferro-f.jpg',
    cardDescription: 'Gênio, bilionário, playboy, filantropo! Eu sou o homem de ferro!',
    cardAttr1: '70',
    cardAttr2: '60',
    cardAttr3: '85',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Doutor Estranho',
    cardImage: 'https://s.aficionados.com.br/imagens/doutor-estranho-7.jpg',
    cardDescription: 'Eu vim barganhar!',
    cardAttr1: '80',
    cardAttr2: '35',
    cardAttr3: '75',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Viúva Negra',
    cardImage: 'https://s.aficionados.com.br/imagens/poderes-habilidades-2-0.jpg',
    cardDescription: 'Escrever algo sobre',
    cardAttr1: '35',
    cardAttr2: '40',
    cardAttr3: '60',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Thor',
    cardImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-U-mI_AaR-dZBAwzF6gSiLVdVAZwUYCLsXg&usqp=CAU',
    cardDescription: 'O vingador mais forte?',
    cardAttr1: '88',
    cardAttr2: '65',
    cardAttr3: '40',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Feiticeira Escarlate',
    cardImage: 'https://s.aficionados.com.br/imagens/scarletmagic-0.jpg',
    cardDescription: 'Morava em Westview',
    cardAttr1: '88',
    cardAttr2: '50',
    cardAttr3: '50',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Loki',
    cardImage: 'https://s.aficionados.com.br/imagens/origem-9-0.jpg',
    cardDescription: 'Deus do fogo, da trapaça e da travessura. Deus fraco.',
    cardAttr1: '65',
    cardAttr2: '50',
    cardAttr3: '60',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Gavião Arqueiro',
    cardImage: 'https://s.aficionados.com.br/imagens/hawkeye-760x428_cke.jpg',
    cardDescription: 'Atira umas flechas como ninguém',
    cardAttr1: '35',
    cardAttr2: '35',
    cardAttr3: '65',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Visão',
    cardImage: 'https://s.aficionados.com.br/imagens/visa-o-marvel_cke.jpg',
    cardDescription: 'Você está familiarizado com o experimento mental O Navio de Teseu?',
    cardAttr1: '85',
    cardAttr2: '65',
    cardAttr3: '90',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Homem Formiga',
    cardImage: 'https://s.aficionados.com.br/imagens/ant-man-flying-0.jpg',
    cardDescription: 'Cara, eu tenho mestrado em engenharia elétrica. Vou me virar.',
    cardAttr1: '85',
    cardAttr2: '65',
    cardAttr3: '90',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
];

export default array;
