const Data = [
  {
    cardName: 'Bird EggBomb',
    cardAttr1: 90,
    cardAttr2: 90,
    cardAttr3: 30,
    cardDescription: 'aushduashduhasudhasu',
    cardTrunfo: false,
    cardRare: 'raro',
    cardImage: 'https://storage.googleapis.com/assets.axieinfinity.com/axies/149200/axie/axie-full-transparent.png',
  },
  {
    cardName: 'Aquaman',
    cardAttr1: 65,
    cardAttr2: 65,
    cardAttr3: 70,
    cardDescription: 'aushduashduhasudhasu',
    cardTrunfo: false,
    cardRare: 'normal',
    cardImage: 'https://i.pinimg.com/originals/d4/14/39/d41439baf82665a805eed89c16f5e804.png',
  },
  {
    cardName: 'Kotaro',
    cardAttr1: 70,
    cardAttr2: 90,
    cardAttr3: 50,
    cardDescription: 'aushduashduhasudhasu',
    cardTrunfo: true,
    cardRare: 'normal',
    cardImage: 'https://assets.axieinfinity.com/axies/2054139/axie/axie-full-transparent.png',
  },
  {
    cardName: 'Florzinha',
    cardAttr1: 40,
    cardAttr2: 40,
    cardAttr3: 90,
    cardDescription: 'aushduashduhasudhasu',
    cardTrunfo: false,
    cardRare: 'normal',
    cardImage: 'https://storage.googleapis.com/assets.axieinfinity.com/axies/456/axie/axie-full-transparent.png',
  },
  {
    cardName: 'Starfish',
    cardAttr1: 70,
    cardAttr2: 70,
    cardAttr3: 70,
    cardDescription: 'aushduashduhasudhasu',
    cardTrunfo: false,
    cardRare: 'normal',
    cardImage: 'https://i.pinimg.com/originals/87/22/53/87225318dda164859fecd4c616877860.png',
  },
];

export default Data;
