const raridade = 'muito raro';

const data = [
  {
    cardName: 'One Piece',
    cardDescription: 'One Piece,história de piratas liderados por Monkey D. Luffy',
    cardAttr1: '80',
    cardAttr2: '80',
    cardAttr3: '50',
    cardImage: 'https://rollingstone.uol.com.br/media/uploads/one-piece-live-action-series-seemingly-coming-to-netflix_1fcz.h720.jpg',
    cardRare: raridade,
    cardTrunfo: false,
    del: 'del',
    //   delCard: this.delCard,
  },
  {
    cardName: 'Hunter X Hunter',
    cardDescription: 'A história de Gon Freecss, que pretende se tornar um Hunter',
    cardAttr1: '80',
    cardAttr2: '80',
    cardAttr3: '50',
    cardImage: 'https://quintacapa.com.br/wp-content/uploads/2020/07/Hunter-x-Hunter-hunter-x-hunter-destaque.jpg',
    cardRare: raridade,
    cardTrunfo: false,
    del: 'del',
  //   delCard: this.delCard,
  },
  {
    cardName: 'Jujutsu Kaisen',
    cardDescription: 'O jovem Yuta ganha o controle de um espírito extremamente poderoso',
    cardAttr1: '80',
    cardAttr2: '80',
    cardAttr3: '50',
    cardImage: 'https://minutootaku.com/wp-content/uploads/2021/05/Review-Jujutsu-Kaisen-mais-do-mesmo-ou-mesmo-do-mais.jpg',
    cardRare: raridade,
    cardTrunfo: false,
    del: 'del',
  //   delCard: this.delCard,
  },
  {
    cardName: 'Death Note',
    cardDescription: 'O Death Note mata pessoas cujo nome são escritos',
    cardAttr1: '80',
    cardAttr2: '80',
    cardAttr3: '50',
    cardImage: 'https://s.aficionados.com.br/imagens/death-note-3_cke.jpg',
    cardRare: raridade,
    cardTrunfo: false,
    del: 'del',
  //   delCard: this.delCard,
  },
  {
    cardName: 'One-Punch Man',
    cardDescription: 'O homem de um soco so.',
    cardAttr1: '80',
    cardAttr2: '80',
    cardAttr3: '50',
    cardImage: 'https://s.aficionados.com.br/imagens/one-punch-man-2_cke.jpg',
    cardRare: raridade,
    cardTrunfo: false,
    del: 'del',
  //   delCard: this.delCard,
  },
  {
    cardName: 'Kimetsu no Yaiba',
    cardDescription: 'O jovem Tanjirō Kamado se transforma em um damon slayer',
    cardAttr1: '80',
    cardAttr2: '80',
    cardAttr3: '50',
    cardImage: 'https://s.aficionados.com.br/imagens/kimetsu-no-yaiba-0_cke.jpg',
    cardRare: raridade,
    cardTrunfo: false,
    del: 'del',
  //   delCard: this.delCard,
  },

];

export default data;
