const data = [
  {
    cardAttr1: '60',
    cardAttr2: '80',
    cardAttr3: '30',
    cardDescription: 'Foi um dos maiores e mais feroz carnívoros',
    cardImage: 'https://www.dododex.com/media/creature/rex.png',
    cardName: 'Rex',
    cardRare: 'muito raro',
    cardTrunfo: true,
  },
  {
    cardAttr1: '30',
    cardAttr2: '30',
    cardAttr3: '90',
    cardDescription: 'Utahraptors eram agressivos e tendiam a viajar em pequenas matilhas de caça',
    cardImage: 'https://www.dododex.com/media/creature/raptor.png',
    cardName: 'Raptor',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardAttr1: '90',
    cardAttr2: '30',
    cardAttr3: '20',
    cardDescription: 'Entre as criaturas gigantes que já existiram, o Brontosaurus foi o maior do que se tem informação. ',
    cardImage: 'https://www.dododex.com/media/creature/brontosaurus.png',
    cardName: 'Bronto',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
  {
    cardAttr1: '40',
    cardAttr2: '30',
    cardAttr3: '60',
    cardDescription: 'Os Dilophosaurus Eram dinossauros terópodes de tamanho médio e predadores agressivos.',
    cardImage: 'https://www.dododex.com/media/creature/dilophosaur.png',
    cardName: 'Dilo',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardAttr1: '60',
    cardAttr2: '30',
    cardAttr3: '30',
    cardDescription: 'O Triceratops foi um herbívoro de grande porte. Normalmente um animal muito dócil a pastar.',
    cardImage: 'https://www.dododex.com/media/creature/triceratops.png',
    cardName: 'Trike',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardAttr1: '80',
    cardAttr2: '30',
    cardAttr3: '20',
    cardDescription: 'O Stegosaurus tinha fileiras de placas emparelhadas ao longo das suas costas.',
    cardImage: 'https://www.dododex.com/media/creature/stegosaurus.png',
    cardName: 'Stego',
    cardRare: 'raro',
    cardTrunfo: false,
  },
];

export default data;
